/* This file was generated by SableCC (http://www.sablecc.org/). */
#include <stdlib.h>
#include "tables_nit.h"

static const int lexer_goto_row1[] = {
	16,
	9, 9, 1,
	10, 10, 2,
	13, 13, 3,
	32, 32, 4,
	34, 34, 5,
	39, 39, 6,
	44, 44, 7,
	45, 45, 8,
	46, 46, 9,
	48, 48, 10,
	49, 57, 11,
	58, 58, 12,
	59, 59, 13,
	65, 90, 14,
	95, 95, 15,
	97, 122, 16
};
static const int lexer_goto_row2[] = {
	2,
	9, 9, 1,
	32, 32, 4
};
static const int lexer_goto_row4[] = {
	1,
	10, 10, 17
};
static const int lexer_goto_row5[] = {
	1,
	9, 32, -3
};
static const int lexer_goto_row6[] = {
	7,
	0, 9, 18,
	11, 12, 18,
	14, 33, 18,
	34, 34, 19,
	35, 91, 18,
	92, 92, 20,
	93, 255, 18
};
static const int lexer_goto_row7[] = {
	6,
	0, 9, 21,
	11, 12, 21,
	14, 38, 21,
	40, 91, 21,
	92, 92, 22,
	93, 255, 21
};
static const int lexer_goto_row9[] = {
	1,
	48, 57, 23
};
static const int lexer_goto_row10[] = {
	9,
	48, 57, 24,
	65, 65, 25,
	66, 66, 26,
	69, 69, 27,
	87, 87, 28,
	97, 97, 29,
	98, 98, 30,
	101, 101, 31,
	119, 119, 32
};
static const int lexer_goto_row11[] = {
	6,
	46, 46, 33,
	48, 57, 11,
	65, 95, -2,
	97, 119, 16,
	120, 120, 34,
	121, 122, 16
};
static const int lexer_goto_row12[] = {
	2,
	46, 95, -12,
	97, 122, 16
};
static const int lexer_goto_row14[] = {
	3,
	0, 9, 35,
	11, 12, 35,
	14, 255, 35
};
static const int lexer_goto_row15[] = {
	2,
	48, 57, 36,
	65, 122, -2
};
static const int lexer_goto_row16[] = {
	1,
	48, 122, -16
};
static const int lexer_goto_row17[] = {
	1,
	48, 122, -16
};
static const int lexer_goto_row19[] = {
	1,
	0, 255, -7
};
static const int lexer_goto_row21[] = {
	7,
	0, 9, 37,
	11, 12, 37,
	14, 33, 37,
	34, 34, 38,
	35, 91, 37,
	92, 92, 39,
	93, 255, 37
};
static const int lexer_goto_row22[] = {
	1,
	39, 39, 40
};
static const int lexer_goto_row23[] = {
	5,
	0, 9, 41,
	11, 12, 41,
	14, 119, 41,
	120, 120, 42,
	121, 255, 41
};
static const int lexer_goto_row24[] = {
	1,
	48, 57, 23
};
static const int lexer_goto_row25[] = {
	1,
	48, 57, 24
};
static const int lexer_goto_row26[] = {
	4,
	68, 68, 43,
	83, 83, 44,
	100, 100, 45,
	115, 115, 46
};
static const int lexer_goto_row27[] = {
	6,
	76, 76, 47,
	85, 85, 48,
	89, 89, 49,
	108, 108, 50,
	117, 117, 51,
	121, 121, 52
};
static const int lexer_goto_row28[] = {
	4,
	78, 78, 53,
	81, 81, 54,
	110, 110, 55,
	113, 113, 56
};
static const int lexer_goto_row29[] = {
	2,
	79, 79, 57,
	111, 111, 58
};
static const int lexer_goto_row30[] = {
	1,
	68, 115, -27
};
static const int lexer_goto_row31[] = {
	1,
	76, 121, -28
};
static const int lexer_goto_row32[] = {
	1,
	78, 113, -29
};
static const int lexer_goto_row33[] = {
	1,
	79, 111, -30
};
static const int lexer_goto_row34[] = {
	1,
	48, 57, 24
};
static const int lexer_goto_row35[] = {
	6,
	48, 57, 59,
	65, 70, 60,
	71, 90, 14,
	95, 95, 15,
	97, 102, 61,
	103, 122, 16
};
static const int lexer_goto_row36[] = {
	1,
	0, 255, -15
};
static const int lexer_goto_row37[] = {
	1,
	48, 122, -16
};
static const int lexer_goto_row38[] = {
	1,
	0, 255, -7
};
static const int lexer_goto_row39[] = {
	1,
	0, 255, -7
};
static const int lexer_goto_row40[] = {
	1,
	0, 255, -22
};
static const int lexer_goto_row42[] = {
	1,
	39, 39, 62
};
static const int lexer_goto_row43[] = {
	4,
	39, 39, 62,
	48, 57, 63,
	65, 70, 64,
	97, 102, 65
};
static const int lexer_goto_row44[] = {
	2,
	68, 68, 66,
	100, 100, 67
};
static const int lexer_goto_row45[] = {
	2,
	67, 67, 68,
	99, 99, 69
};
static const int lexer_goto_row46[] = {
	1,
	68, 100, -45
};
static const int lexer_goto_row47[] = {
	1,
	67, 99, -46
};
static const int lexer_goto_row48[] = {
	2,
	79, 79, 70,
	111, 111, 71
};
static const int lexer_goto_row49[] = {
	2,
	82, 82, 72,
	114, 114, 73
};
static const int lexer_goto_row50[] = {
	2,
	84, 84, 74,
	116, 116, 75
};
static const int lexer_goto_row51[] = {
	1,
	79, 111, -49
};
static const int lexer_goto_row52[] = {
	1,
	82, 114, -50
};
static const int lexer_goto_row53[] = {
	1,
	84, 116, -51
};
static const int lexer_goto_row54[] = {
	2,
	68, 68, 76,
	100, 100, 77
};
static const int lexer_goto_row55[] = {
	2,
	85, 85, 78,
	117, 117, 79
};
static const int lexer_goto_row56[] = {
	1,
	68, 100, -55
};
static const int lexer_goto_row57[] = {
	1,
	85, 117, -56
};
static const int lexer_goto_row58[] = {
	2,
	82, 82, 80,
	114, 114, 81
};
static const int lexer_goto_row59[] = {
	1,
	82, 114, -59
};
static const int lexer_goto_row60[] = {
	1,
	48, 122, -36
};
static const int lexer_goto_row61[] = {
	1,
	48, 122, -36
};
static const int lexer_goto_row62[] = {
	1,
	48, 122, -36
};
static const int lexer_goto_row64[] = {
	3,
	48, 57, 82,
	65, 70, 83,
	97, 102, 84
};
static const int lexer_goto_row65[] = {
	1,
	48, 102, -65
};
static const int lexer_goto_row66[] = {
	1,
	48, 102, -65
};
static const int lexer_goto_row67[] = {
	2,
	82, 82, 85,
	114, 114, 86
};
static const int lexer_goto_row68[] = {
	1,
	82, 114, -68
};
static const int lexer_goto_row69[] = {
	2,
	73, 73, 87,
	105, 105, 88
};
static const int lexer_goto_row70[] = {
	1,
	73, 105, -70
};
static const int lexer_goto_row71[] = {
	2,
	67, 67, 89,
	99, 99, 90
};
static const int lexer_goto_row72[] = {
	1,
	67, 99, -72
};
static const int lexer_goto_row73[] = {
	2,
	78, 78, 91,
	110, 110, 92
};
static const int lexer_goto_row74[] = {
	1,
	78, 110, -74
};
static const int lexer_goto_row75[] = {
	2,
	69, 69, 93,
	101, 101, 94
};
static const int lexer_goto_row76[] = {
	1,
	69, 101, -76
};
static const int lexer_goto_row77[] = {
	5,
	0, 9, 95,
	10, 10, 96,
	11, 12, 95,
	13, 13, 97,
	14, 255, 95
};
static const int lexer_goto_row78[] = {
	1,
	0, 255, -78
};
static const int lexer_goto_row79[] = {
	2,
	65, 65, 98,
	97, 97, 99
};
static const int lexer_goto_row80[] = {
	1,
	65, 97, -80
};
static const int lexer_goto_row81[] = {
	2,
	68, 68, 100,
	100, 100, 101
};
static const int lexer_goto_row82[] = {
	1,
	68, 100, -82
};
static const int lexer_goto_row83[] = {
	1,
	39, 39, 102
};
static const int lexer_goto_row84[] = {
	1,
	39, 39, 102
};
static const int lexer_goto_row85[] = {
	1,
	39, 39, 102
};
static const int lexer_goto_row86[] = {
	2,
	83, 83, 103,
	115, 115, 104
};
static const int lexer_goto_row87[] = {
	1,
	83, 115, -87
};
static const int lexer_goto_row88[] = {
	2,
	73, 73, 105,
	105, 105, 106
};
static const int lexer_goto_row89[] = {
	1,
	73, 105, -89
};
static const int lexer_goto_row90[] = {
	2,
	75, 75, 107,
	107, 107, 108
};
static const int lexer_goto_row91[] = {
	1,
	75, 107, -91
};
static const int lexer_goto_row96[] = {
	1,
	0, 255, -78
};
static const int lexer_goto_row97[] = {
	1,
	0, 255, -78
};
static const int lexer_goto_row98[] = {
	3,
	0, 9, 95,
	10, 10, 109,
	11, 255, -78
};
static const int lexer_goto_row99[] = {
	2,
	84, 84, 110,
	116, 116, 111
};
static const int lexer_goto_row100[] = {
	1,
	84, 116, -100
};
static const int lexer_goto_row104[] = {
	2,
	83, 83, 112,
	115, 115, 113
};
static const int lexer_goto_row105[] = {
	1,
	83, 115, -105
};
static const int lexer_goto_row110[] = {
	1,
	0, 255, -78
};
static const int lexer_goto_row111[] = {
	2,
	69, 69, 114,
	101, 101, 115
};
static const int lexer_goto_row112[] = {
	1,
	69, 101, -112
};
static const int lexer_goto_row_null[] = {0};
const int* const lexer_goto_table[] = {
	lexer_goto_row1,
	lexer_goto_row2,
	lexer_goto_row_null,
	lexer_goto_row4,
	lexer_goto_row5,
	lexer_goto_row6,
	lexer_goto_row7,
	lexer_goto_row_null,
	lexer_goto_row9,
	lexer_goto_row10,
	lexer_goto_row11,
	lexer_goto_row12,
	lexer_goto_row_null,
	lexer_goto_row14,
	lexer_goto_row15,
	lexer_goto_row16,
	lexer_goto_row17,
	lexer_goto_row_null,
	lexer_goto_row19,
	lexer_goto_row_null,
	lexer_goto_row21,
	lexer_goto_row22,
	lexer_goto_row23,
	lexer_goto_row24,
	lexer_goto_row25,
	lexer_goto_row26,
	lexer_goto_row27,
	lexer_goto_row28,
	lexer_goto_row29,
	lexer_goto_row30,
	lexer_goto_row31,
	lexer_goto_row32,
	lexer_goto_row33,
	lexer_goto_row34,
	lexer_goto_row35,
	lexer_goto_row36,
	lexer_goto_row37,
	lexer_goto_row38,
	lexer_goto_row39,
	lexer_goto_row40,
	lexer_goto_row_null,
	lexer_goto_row42,
	lexer_goto_row43,
	lexer_goto_row44,
	lexer_goto_row45,
	lexer_goto_row46,
	lexer_goto_row47,
	lexer_goto_row48,
	lexer_goto_row49,
	lexer_goto_row50,
	lexer_goto_row51,
	lexer_goto_row52,
	lexer_goto_row53,
	lexer_goto_row54,
	lexer_goto_row55,
	lexer_goto_row56,
	lexer_goto_row57,
	lexer_goto_row58,
	lexer_goto_row59,
	lexer_goto_row60,
	lexer_goto_row61,
	lexer_goto_row62,
	lexer_goto_row_null,
	lexer_goto_row64,
	lexer_goto_row65,
	lexer_goto_row66,
	lexer_goto_row67,
	lexer_goto_row68,
	lexer_goto_row69,
	lexer_goto_row70,
	lexer_goto_row71,
	lexer_goto_row72,
	lexer_goto_row73,
	lexer_goto_row74,
	lexer_goto_row75,
	lexer_goto_row76,
	lexer_goto_row77,
	lexer_goto_row78,
	lexer_goto_row79,
	lexer_goto_row80,
	lexer_goto_row81,
	lexer_goto_row82,
	lexer_goto_row83,
	lexer_goto_row84,
	lexer_goto_row85,
	lexer_goto_row86,
	lexer_goto_row87,
	lexer_goto_row88,
	lexer_goto_row89,
	lexer_goto_row90,
	lexer_goto_row91,
	lexer_goto_row_null,
	lexer_goto_row_null,
	lexer_goto_row_null,
	lexer_goto_row_null,
	lexer_goto_row96,
	lexer_goto_row97,
	lexer_goto_row98,
	lexer_goto_row99,
	lexer_goto_row100,
	lexer_goto_row_null,
	lexer_goto_row_null,
	lexer_goto_row_null,
	lexer_goto_row104,
	lexer_goto_row105,
	lexer_goto_row_null,
	lexer_goto_row_null,
	lexer_goto_row_null,
	lexer_goto_row_null,
	lexer_goto_row110,
	lexer_goto_row111,
	lexer_goto_row112,
	lexer_goto_row_null,
	lexer_goto_row_null,
	lexer_goto_row_null,
	lexer_goto_row_null
};

const int lexer_accept_table[] = {
	-1,0,1,1,0,-1,-1,8,-1,-1,2,2,7,9,18,18,18,1,-1,5,-1,-1,-1,2,3,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,9,18,-1,5,-1,4,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,6,6,6,4,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,17,17,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,16,16,10,10,17,17,17,-1,-1,11,11,4,-1,-1,13,13,12,12,17,-1,-1,14,14,15,15
};

static int parser_action_row1[] = {
	12,
	-1, 3, 0,
	0, 0, 1,
	8, 0, 2,
	9, 0, 3,
	10, 0, 4,
	11, 0, 5,
	12, 0, 6,
	13, 0, 7,
	14, 0, 8,
	15, 0, 9,
	16, 0, 10,
	17, 0, 11
};
static int parser_action_row2[] = {
	1,
	-1, 1, 4
};
static int parser_action_row3[] = {
	2,
	-1, 3, 2,
	0, 0, 18
};
static int parser_action_row4[] = {
	6,
	-1, 3, 3,
	1, 0, 19,
	3, 0, 20,
	4, 0, 21,
	5, 0, 22,
	17, 0, 23
};
static int parser_action_row5[] = {
	6,
	-1, 3, 4,
	1, 0, 19,
	3, 0, 20,
	4, 0, 21,
	5, 0, 22,
	17, 0, 23
};
static int parser_action_row6[] = {
	6,
	-1, 3, 5,
	1, 0, 19,
	3, 0, 20,
	4, 0, 21,
	5, 0, 22,
	17, 0, 23
};
static int parser_action_row7[] = {
	6,
	-1, 3, 6,
	1, 0, 19,
	3, 0, 20,
	4, 0, 21,
	5, 0, 22,
	17, 0, 23
};
static int parser_action_row8[] = {
	6,
	-1, 3, 7,
	1, 0, 19,
	3, 0, 20,
	4, 0, 21,
	5, 0, 22,
	17, 0, 23
};
static int parser_action_row9[] = {
	6,
	-1, 3, 8,
	1, 0, 19,
	3, 0, 20,
	4, 0, 21,
	5, 0, 22,
	17, 0, 23
};
static int parser_action_row10[] = {
	6,
	-1, 3, 9,
	1, 0, 19,
	3, 0, 20,
	4, 0, 21,
	5, 0, 22,
	17, 0, 23
};
static int parser_action_row11[] = {
	1,
	-1, 1, 0
};
static int parser_action_row12[] = {
	7,
	-1, 1, 17,
	1, 0, 19,
	3, 0, 20,
	4, 0, 21,
	5, 0, 22,
	6, 0, 31,
	17, 0, 23
};
static int parser_action_row13[] = {
	2,
	-1, 3, 12,
	18, 2, -1
};
static int parser_action_row14[] = {
	1,
	-1, 1, 33
};
static int parser_action_row15[] = {
	12,
	-1, 3, 14,
	0, 0, 34,
	8, 0, 35,
	9, 0, 3,
	10, 0, 4,
	11, 0, 5,
	12, 0, 6,
	13, 0, 7,
	14, 0, 8,
	15, 0, 9,
	16, 0, 36,
	17, 0, 37
};
static int parser_action_row16[] = {
	3,
	-1, 3, 15,
	0, 0, 40,
	8, 0, 41
};
static int parser_action_row17[] = {
	3,
	-1, 3, 16,
	0, 0, 42,
	8, 0, 43
};
static int parser_action_row18[] = {
	12,
	-1, 3, 17,
	0, 0, 1,
	8, 0, 2,
	9, 0, 3,
	10, 0, 4,
	11, 0, 5,
	12, 0, 6,
	13, 0, 7,
	14, 0, 8,
	15, 0, 9,
	16, 0, 44,
	17, 0, 11
};
static int parser_action_row19[] = {
	1,
	-1, 1, 6
};
static int parser_action_row20[] = {
	1,
	-1, 1, 22
};
static int parser_action_row21[] = {
	1,
	-1, 1, 23
};
static int parser_action_row22[] = {
	1,
	-1, 1, 24
};
static int parser_action_row23[] = {
	1,
	-1, 1, 25
};
static int parser_action_row24[] = {
	1,
	-1, 1, 21
};
static int parser_action_row25[] = {
	1,
	-1, 1, 26
};
static int parser_action_row26[] = {
	1,
	-1, 1, 27
};
static int parser_action_row27[] = {
	1,
	-1, 1, 28
};
static int parser_action_row28[] = {
	1,
	-1, 1, 29
};
static int parser_action_row29[] = {
	1,
	-1, 1, 30
};
static int parser_action_row30[] = {
	1,
	-1, 1, 31
};
static int parser_action_row31[] = {
	1,
	-1, 1, 32
};
static int parser_action_row32[] = {
	1,
	-1, 1, 16
};
static int parser_action_row33[] = {
	1,
	-1, 1, 18
};
static int parser_action_row34[] = {
	2,
	-1, 1, 19,
	7, 0, 47
};
static int parser_action_row35[] = {
	1,
	-1, 1, 5
};
static int parser_action_row36[] = {
	2,
	-1, 3, 35,
	0, 0, 48
};
static int parser_action_row37[] = {
	1,
	-1, 1, 2
};
static int parser_action_row38[] = {
	6,
	-1, 1, 17,
	1, 0, 19,
	3, 0, 20,
	4, 0, 21,
	5, 0, 22,
	17, 0, 23
};
static int parser_action_row39[] = {
	3,
	-1, 3, 38,
	0, 0, 49,
	8, 0, 50
};
static int parser_action_row40[] = {
	3,
	-1, 3, 39,
	0, 0, 51,
	8, 0, 52
};
static int parser_action_row41[] = {
	1,
	-1, 1, 8
};
static int parser_action_row42[] = {
	2,
	-1, 3, 41,
	0, 0, 53
};
static int parser_action_row43[] = {
	1,
	-1, 1, 12
};
static int parser_action_row44[] = {
	2,
	-1, 3, 43,
	0, 0, 54
};
static int parser_action_row45[] = {
	1,
	-1, 1, 1
};
static int parser_action_row46[] = {
	1,
	-1, 1, 34
};
static int parser_action_row47[] = {
	12,
	-1, 3, 46,
	0, 0, 34,
	8, 0, 35,
	9, 0, 3,
	10, 0, 4,
	11, 0, 5,
	12, 0, 6,
	13, 0, 7,
	14, 0, 8,
	15, 0, 9,
	16, 0, 55,
	17, 0, 37
};
static int parser_action_row48[] = {
	2,
	-1, 3, 47,
	17, 0, 56
};
static int parser_action_row49[] = {
	1,
	-1, 1, 7
};
static int parser_action_row50[] = {
	1,
	-1, 1, 9
};
static int parser_action_row51[] = {
	2,
	-1, 3, 50,
	0, 0, 57
};
static int parser_action_row52[] = {
	1,
	-1, 1, 13
};
static int parser_action_row53[] = {
	2,
	-1, 3, 52,
	0, 0, 58
};
static int parser_action_row54[] = {
	1,
	-1, 1, 10
};
static int parser_action_row55[] = {
	1,
	-1, 1, 14
};
static int parser_action_row56[] = {
	1,
	-1, 1, 3
};
static int parser_action_row57[] = {
	1,
	-1, 1, 20
};
static int parser_action_row58[] = {
	1,
	-1, 1, 11
};
static int parser_action_row59[] = {
	1,
	-1, 1, 15
};

const int* const parser_action_table[] = {
	parser_action_row1,
	parser_action_row2,
	parser_action_row3,
	parser_action_row4,
	parser_action_row5,
	parser_action_row6,
	parser_action_row7,
	parser_action_row8,
	parser_action_row9,
	parser_action_row10,
	parser_action_row11,
	parser_action_row12,
	parser_action_row13,
	parser_action_row14,
	parser_action_row15,
	parser_action_row16,
	parser_action_row17,
	parser_action_row18,
	parser_action_row19,
	parser_action_row20,
	parser_action_row21,
	parser_action_row22,
	parser_action_row23,
	parser_action_row24,
	parser_action_row25,
	parser_action_row26,
	parser_action_row27,
	parser_action_row28,
	parser_action_row29,
	parser_action_row30,
	parser_action_row31,
	parser_action_row32,
	parser_action_row33,
	parser_action_row34,
	parser_action_row35,
	parser_action_row36,
	parser_action_row37,
	parser_action_row38,
	parser_action_row39,
	parser_action_row40,
	parser_action_row41,
	parser_action_row42,
	parser_action_row43,
	parser_action_row44,
	parser_action_row45,
	parser_action_row46,
	parser_action_row47,
	parser_action_row48,
	parser_action_row49,
	parser_action_row50,
	parser_action_row51,
	parser_action_row52,
	parser_action_row53,
	parser_action_row54,
	parser_action_row55,
	parser_action_row56,
	parser_action_row57,
	parser_action_row58,
	parser_action_row59
};

static int parser_goto_row1[] = {
	1,
	-1, 12
};
static int parser_goto_row2[] = {
	2,
	-1, 13,
	17, 45
};
static int parser_goto_row3[] = {
	2,
	-1, 14,
	17, 46
};
static int parser_goto_row4[] = {
	3,
	-1, 15,
	14, 38,
	46, 38
};
static int parser_goto_row5[] = {
	1,
	-1, 32
};
static int parser_goto_row6[] = {
	8,
	-1, 33,
	3, 24,
	4, 25,
	5, 26,
	6, 27,
	7, 28,
	8, 29,
	9, 30
};
static int parser_goto_row7[] = {
	3,
	-1, 16,
	14, 39,
	46, 39
};
static int parser_goto_row8[] = {
	1,
	-1, 17
};

const int* const parser_goto_table[] = {
	parser_goto_row1,
	parser_goto_row2,
	parser_goto_row3,
	parser_goto_row4,
	parser_goto_row5,
	parser_goto_row6,
	parser_goto_row7,
	parser_goto_row8
};
